### PR TITLE
Support keys larger > 1024 characters

### LINKED ISSUE #942: Support keys longer than 1024 characters
**Is your feature request related to a problem? Please describe.**

I have a usecase for parsing pnpm-lock.yaml files using this library. Unfortunately, PNPM does not really seem to be concerned with the spec when it comes to key-length (spec says 1024 is the max, pnpm emitted a key of length >1080 in one of my testcases).

**Describe the solution you'd like**

I'd love to have a new function on the `DeserializerBuilder()`, maybe something like `.WithMaxKeyLength()` that allows defining a larger than the default value when deserializing.

**Describe alternatives you've considered**

1. Shortening the keys myself with a regex replace or something like that - I don't have a requirement for accurate keys in this specific case at least not for the long ones
2. Opening an issue with pnpm to adhere to the spec but given that the keys are relevant for them for faster caching, I am not sure this will have much chance of actually going through

**Additional context**

Reprocase:

```c#
const string yamlString = """
                   '@angular/material@17.3.1(@angular/animations@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4)))(@angular/cdk@17.3.1(@angular/common@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/common@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(@angular/forms@17.3.4(@angular/common@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(@angular/platform-browser@17.3.4(@angular/animations@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4)))(@angular/common@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4)))(rxjs@7.8.1))(@angular/platform-browser@17.3.4(@angular/animations@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4)))(@angular/common@17.3.4(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4))(rxjs@7.8.1))(@angular/core@17.3.4(rxjs@7.8.1)(zone.js@0.14.4)))(rxjs@7.8.1)':
                     dependencies: []
                   """;
var deserializer = new DeserializerBuilder().Build();
var yaml = deserializer.Deserialize<Dictionary<string, object>>(yamlString);
```

Error:

```
Unhandled exception. (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1089, Idx: 1088): Exception during deserialization
```

### PR DESCRIPTION
**Pull request by EdwardCooke**
Fixes #942 
To use, new up the scanner and specify the overriden maximum key length, when deserializing use the scanner. Here is an example:

```csharp
[Fact]
public void SupportRealyLongStrings()
{
    var longKey = string.Concat(Enumerable.Repeat("x", 1500));
    var yamlString = $"{longKey}: value";
    var scanner = new Scanner(new StringReader(yamlString), true, 1500);
    var deserializer = new DeserializerBuilder().Build();
    var yaml = deserializer.Deserialize<Dictionary<string, object>>(scanner);
    Assert.Equal(longKey, $"'{yaml.Keys.First()}'");
}
```

### CODE REVIEW

**Comment by mvarendorff2** [comment]
Hey there, thanks so much for this change! Quick question because I might be missing something: Passing the scanner as argument to `.Deserialize` as shown in the snippet above causes a compiler error for me (`.Deserialize` only takes `string`, `TextReader` or `IParser` as arguments). I updated to 16.1.0.

**Comment by EdwardCooke** [comment]
I missed a line in my example. You have to new up a parser and pass that in. I’ll update the example shortly.

**Comment by EdwardCooke** [comment]
Updated.

**Comment by mvarendorff2** [comment]
Brilliant, thank you so much!

**Pull request merged**
