### PR TITLE
Line breaks between sections

### PR DESCRIPTION
**Pull request by jarmanso7**
As I am trying to help with the question [YAML C# Add new line between items](https://stackoverflow.com/questions/77518750/yaml-c-sharp-add-new-line-between-items) at Stackoverflow, I am also interested in the feature in the pull request #804, which seems to have stalled due to not merging from a branch instead of merging from master thus failing the build.

I decided to clone, cherry-pick the relevant commits and create a pull request myself.

### CODE REVIEW

**Comment by EdwardCooke** [comment]
I really want this to allow people to put in anything they want, not just a new line only.

**Comment by Strandfelt** [comment]
How come you closed this PR @jarmanso7? Was it declined? I can't seem to find any documentation about this being implemented.

**Comment by EdwardCooke** [comment]
I was hoping it would have been changed to allow people to put in arbitrary comments. Not just empty lines.

**Comment by EdwardCooke** [comment]
I think there’s a bug in the UI. At least on mobile. For the past few days I’ve had to download the log and view it from that. 

```
C:\projects\yamldotnet\YamlDotNet\Serialization\SerializerBuilder.cs(691,13): error IDE0074: Use compound assignment (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074) [C:\projects\yamldotnet\YamlDotNet\YamlDotNet.csproj::TargetFramework=net47]
[00:02:16] C:\projects\yamldotnet\YamlDotNet\Serialization\DeserializerBuilder.cs(488,13): error IDE0074: Use compound assignment (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074) [C:\projects\yamldotnet\YamlDotNet\YamlDotNet.csproj::TargetFramework=net47]
```

**Comment by jarmanso7** [comment]
@Strandfelt I am sorry, I wasn't aware I closed this PR somehow. It shows I "closed this by deleting the head repository on Feb 4, 2024", but I don't remember the context behing this action.

**Pull request closed without merging**
