### PR TITLE
fix serializing double.MaxValue #177

### PR DESCRIPTION
**Pull request by vwxyzh**
use "G17", see: [Standard Numeric Format Strings](https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx)

### CODE REVIEW

**Comment by aaubry** [comment]
Hi! Thanks for contributing. Could you add unit test(s) for this feature? This is necessary to ensure that this won't be broken on a future change.

**Comment by vwxyzh** [comment]
unit test added.

**Comment by aaubry** [comment]
I have another question. Shouldn't we use the "R" (roundtrip) format spectfier instead?

> The round-trip specifier guarantees that a numeric value converted to a string will be parsed back into the same numeric value. When a numeric value is formatted using this specifier, it is first tested using the general format, with 15 spaces of precision for a Double and 7 spaces of precision for a Single. If the value is successfully parsed back to the same numeric value, it is formatted using the general format specifier. However, if the value is not successfully parsed back to the same numeric value, then the value is formatted using 17 digits of precision for a Double and 9 digits of precision for a Single. Although a precision specifier can be appended to the round-trip format specifier, it is ignored. Round trips are given precedence over precision when using this specifier. This format is supported by floating-point types only.

http://www.hanselman.com/blog/WhyYouCantDoubleParseDoubleMaxValueToStringOrSystemOverloadExceptionsWhenUsingDoubleParse.aspx

**Comment by vwxyzh** [comment]
in [Standard Numeric Format Strings](https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx)
>**Important**
>In some cases, Double values formatted with the "R" standard numeric format string do not successfully round-trip if compiled using the /platform:x64 or /platform:anycpu switches and run on 64-bit systems. See the following paragraph for more information.

**Comment by aaubry** [comment]
Thanks for the clarification. I had to refactor the tests, because your changes deleted important tests that checked the correct serialization of constants such as infinitty.

**Pull request merged**
