### PR TITLE
Commit .NET Core version of YamlDotNet with unit tests.

### PR DESCRIPTION
**Pull request by alexinea**
本次提交为 .NET Core 版本的初次提交，因此为全项目完整提交，包括：
+ YamlDotNet.Standard ，项目的 .net core 版本
+ YamlDotNet.Standard.Tests，对应的单元测试项目

本次提交基于 .NETStrandard1.6，待到.NETStrandard2.0发布后升级到2.0

本次提交仅包含 Unit Tests，暂不包含性能测试和AOTTests，期待其它贡献者补完。

本次提交不包含 Samples，期待其它贡献者补完。

### CODE REVIEW

**Comment by alexinea** [comment]
image

All unit tests passed.

image

and the coverage tree screenshot

**Comment by aaubry** [comment]
Hi, thanks for contributing. I'm sorry, but it does not make sense to duplicate every file in the project. I cannot accept this PR like this. Also, please explain what this achieves. I understand that this is to build the library on .NET core, but what is the purpose of this? As far as I can tell, you can already use the YamlDotNet NuGet package on .NET core, so I see no point in this. Am I missing something?

**Comment by alexinea** [comment]
Hi @aaubry , thank you for your reply. I understand what you mean...uh... it seems to look like I did something unnecessary besides one new version of *project.json* ... (;′⌒`)

**Comment by aaubry** [comment]
I am closing this as .NET Core support of this was completed on [another PR](https://github.com/aaubry/YamlDotNet/pull/255), which has been merged into master. I have released version [4.2.0](https://www.nuget.org/packages/YamlDotNet/4.2.0) which contains the new `netstandard1.3` assembly.
If you find anything that is not as it should, please open an issue.

**Pull request closed without merging**
