### PR TITLE
Port to .NET Standard

### PR DESCRIPTION
**Pull request by nbarbettini**
Hey @aaubry, I took another stab at porting this library to .NET Standard. The tooling in VS2017 is updated now, and it no longer requires adding an xproj/project.json file. This PR should supercede #210 and #240.

I tried to keep the changes as minimal as possible so everything else will still work (fingers crossed).

Like before, the library targets .NET Framework 3.5. However, it also now targets .NET Standard 1.3 (.NET Standard is basically an evolution of the idea of PCLs, see [here](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)). All the tests pass, and I think all the other build profiles shouldn't be affected.

The only todo here is fixing the assembly versioning. I think it's being added by the Cake build script? I didn't quite follow it.

### CODE REVIEW

**Comment by nbarbettini** [comment]
FYI, the AppVeyor build is failing because it's using an older version of MSBuild. I think it will build fine if you switch the Build Worker Image to Visual Studio 2017.

**Comment by aaubry** [comment]
Thanks, I'll take a look and try to make it build in CI.

**Comment by conniey** [comment]
@aaubry Any updates on this PR? :)  Is there any help you need?

**Comment by conniey** [comment]
For the travis-ci build, since it is running on Ubuntu, there needs to be some changes made because of this issue: https://github.com/dotnet/sdk/issues/335.

I have a [PR](https://github.com/sillsdev/icu-dotnet/pull/37) for a similar project where I had to get a .NET Core project that targeted the full .NET framework and .NET Core building.  There are steps under "Building on Linux (tested on Ubuntu 16.04)" that could help.

**Comment by aaubry** [comment]
Sorry, I was unable to reply sooner. I will first start to make this build on AppVeyor. The Travis build is only to build on mono with `--aot=full`, so there's no need to configure it for .NET Core.

**Comment by aaubry** [comment]
So I changed the AppVeyor.yml file to use VS2017, but [the build still fails](https://ci.appveyor.com/project/aaubry/yamldotnet). It seems to be failing due .NET core not understanding the `Assembly*Version` attributes. It's fine if they are omitted from the .NET Core build, as it already happens with the portable build, but when targeting the full framework, I want to keep them.

I noticed that the csproj was changed to specify
```xml
<TargetFrameworks>net35;netstandard1.3</TargetFrameworks>
```
That's probably the cause of the problems. The `TargetFrameworks` property should probably be set to a specific value for each configuration.

Also, when I try to build locally on my linux machine (I don't have a Windows machine available atm), xbuild fails with the following error:

```
========================================
Build
========================================
Executing task: Build
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors
/home/aaubry/Work/YamlDotNet/YamlDotNet.sln:  warning : /home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj: The default XML namespace of the pro
ject must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer
/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
/home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj: error : /home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj: The default XML namespace
 of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.co
m/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 fo
rmat.
An error occurred when executing task 'Build'.
Error: XBuild: Process returned an error (exit code 1).
```

I need your help to sort out these issues. Regarding building on Linux, this is  I guess that I need to install something, but I don't know what.

**Comment by aaubry** [comment]
From the build log, there is a `YamlDotNet.AssemblyInfo.cs` file, but I don't see it in the source tree. Is this file being generated? If so, why?

**Comment by aaubry** [comment]
I figured that I needed to add `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to the project to fix the AssemblyInfo bit.
Now there's another issue with the VS2017 image on AppVeyor. It seems that [the portable class library targets are missing](https://ci.appveyor.com/project/aaubry/yamldotnet/build/4.1.1-nbarbettini-netstandard0368). I can't go further without fixing this issue.

**Comment by Bond-009** [comment]
To build on Linux you need the .Net Core sdk 
https://www.microsoft.com/net/core

**Comment by aaubry** [comment]
I've installed the .NET Core sdk but the build still fails, now with a slightly different error:
```
========================================
Build
========================================
Executing task: Build
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors
/home/aaubry/Work/YamlDotNet/YamlDotNet.sln:  warning : /home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/home/aaubry/Work/YamlDotNet/YamlDotNet.sln: error : An item with the same key has already been added.

Unhandled Exception:
System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0008e] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Mono.XBuild.CommandLine.SolutionParser.ParseProjectConfigurationPlatforms (System.String section, System.Collections.Generic.Dictionary`2[TKey,TValue] projectInfos, System.Collections.Generic.Dictionary`2[TKey,TValue] websiteProjectInfos) [0x00100] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Mono.XBuild.CommandLine.SolutionParser.ParseSolution (System.String file, Microsoft.Build.BuildEngine.Project p, Mono.XBuild.CommandLine.RaiseWarningHandler RaiseWarning) [0x007be] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName, Microsoft.Build.BuildEngine.ProjectLoadSettings settings) [0x000ad] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName) [0x00000] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFileInternal (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, System.Collections.IDictionary targetOutputs, Microsoft.Build.BuildEngine.BuildSettings buildFlags, System.String toolsVersion) [0x000b9] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFile (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, System.Collections.IDictionary targetOutputs, Microsoft.Build.BuildEngine.BuildSettings buildFlags, System.String toolsVersion) [0x00008] in <41d66d99749c435eac518d3fedf7a7fa>:0 
An error occurred when executing task 'Build'.
Error: XBuild: Process returned an error (exit code 1).
```

To make it clear, I am using the cake build script:

```
# ./build.sh
```

**Comment by Bond-009** [comment]
The build script uses mono, to build with .Net Core do 'dotnet restore' and 'Dotnet build <project>'

**Comment by conniey** [comment]
I am working on this issue as well (trying to fix the AppVeyor build and trying to get it building on Linux). 

> The build script uses mono, to build with .Net Core do 'dotnet restore' and 'Dotnet build '

Since the project targets both net35 and netstandard1.3, one issue you will encounter is that the dotnet CLI no longer uses mono's framework paths, so it will fail when compiling net35. I mentioned in this comment here: https://github.com/aaubry/YamlDotNet/pull/244#issuecomment-298719428

**Comment by Bond-009** [comment]
@conniey I updated my message. It was originally send on mobile, I fixed it on my PC. You should be able to build it with the provided cmds.

**Comment by conniey** [comment]
@aaubry Hey,  I was able to get it [building on appveyor](https://ci.appveyor.com/project/conniey/yamldotnet/build/4.1.1-netstandard0007), but It is failing because I disabled the Unity Subset v3.5 build.  The reason for that is because a couple of the builds [1](https://ci.appveyor.com/project/conniey/yamldotnet/build/0.0.6), [2](https://ci.appveyor.com/project/conniey/yamldotnet/build/0.0.5) (15hrs) were hanging there forever 
 when trying to execute `.prebuild.ps1`.

```
Submodule path 'BuildUtils': checked out 'a9e693d323b7eca6bab4366ab8344adfbe19a3b9'
Submodule path 'BuildUtils.UnityPrerequisites': checked out 'b83028b96dffdc0bcbff14e4ddeaddd8c94a950d'
.\prebuild.ps1
Extracting Unity Subset v3.5 to C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile
```

Is there a way to workaround for this installation? Also, on my machine, after running prebuild, I get a large number of errors when building Unity Subset v3.5.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3267: The primary reference "System.Drawing", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v3.5,Profile=Unity Subset v3.5". To resolve this problem, either remove the reference "System.Drawing" or retarget your application to a framework version which contains "System.Drawing". [D:\git\conniey\YamlDotNet\YamlDotNet\YamlDotNet.csproj]
```

**Comment by conniey** [comment]
I've gotten it building on Ubuntu 16.04.2 LTS (Xenial) but in Travis-CI, it's having some issues installing the .NET CLI v1.0.3. I'll check into this some more.  Maybe 1.0.0 will work...

* Current branch: [nbarbettini:netstandard compare to: conniey:netstandard](https://github.com/nbarbettini/YamlDotNet/compare/netstandard...conniey:netstandard)

```
The following packages have unmet dependencies:
 dotnet-dev-1.0.3 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
                    Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.4 but it is not going to be installed
                    Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.1 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command "sudo apt-get install -y dotnet-dev-1.0.3" failed and exited with 100 during .
```

**Comment by aaubry** [comment]
Thanks to both for looking into this.

Regarding the Unity Subset issue, I also encountered it, but choose to ignore it temporarily. The code is extracting a zip file, and I should be able to use 7zip.exe or something like that to achieve the same result.

Even with @conniey 's changes, I am still unable to build locally using cake. Since the change to the build.cake was minimal, that's understandable, but without fixing this problem I cannot try to reproduce builds locally. There seems to be tasks specific for dotnetcore, so I'll try to figure out see what changes are needed here, but I find it weird that the script works on Windows without modifications, but not on Linux.

**Comment by conniey** [comment]
@aaubry 

> Even with @conniey 's changes, I am still unable to build locally using cake.

What errors are you encountering when you build the solution in cake?

**What I have Installed**
* Visual Studio 2017 (Community/Enterprise/Professional/etc) with .NET Core Workload ([Instructions here](https://www.microsoft.com/net/core#windowsvs2017))

**Build Steps**
* .\build.ps1 -Target Package

When it fails during build, do you see what version of msbuild it is resolving? It should be 15.* (ie. 15.1.548.43366).  Cake may not be resolving the correct version of MSBuild.

```
========================================
Build-Release-Configurations
========================================
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 5/4/2017 3:31:07 PM.
Project "D:\git\conniey\YamlDotNet\YamlDotNet.sln" on node 1 (Build target(s)).
Building with tools version "15.0".
```

**Comment by aaubry** [comment]
@conniey As I said, I am on **Linux**, so I do not (and cannot) have Visual Studio installed. What I have is mono and the .net core sdk installed. With "regular" .net, the build script worked out of the box. The error is what I mentioned before:
```
========================================
Build
========================================
Executing task: Build
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors
/home/aaubry/Work/YamlDotNet/YamlDotNet.sln:  warning : /home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/home/aaubry/Work/YamlDotNet/YamlDotNet.sln: error : An item with the same key has already been added.

Unhandled Exception:
System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0008e] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Mono.XBuild.CommandLine.SolutionParser.ParseProjectConfigurationPlatforms (System.String section, System.Collections.Generic.Dictionary`2[TKey,TValue] projectInfos, System.Collections.Generic.Dictionary`2[TKey,TValue] websiteProjectInfos) [0x00100] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Mono.XBuild.CommandLine.SolutionParser.ParseSolution (System.String file, Microsoft.Build.BuildEngine.Project p, Mono.XBuild.CommandLine.RaiseWarningHandler RaiseWarning) [0x007be] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName, Microsoft.Build.BuildEngine.ProjectLoadSettings settings) [0x000ad] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName) [0x00000] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFileInternal (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, System.Collections.IDictionary targetOutputs, Microsoft.Build.BuildEngine.BuildSettings buildFlags, System.String toolsVersion) [0x000b9] in <41d66d99749c435eac518d3fedf7a7fa>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFile (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, System.Collections.IDictionary targetOutputs, Microsoft.Build.BuildEngine.BuildSettings buildFlags, System.String toolsVersion) [0x00008] in <41d66d99749c435eac518d3fedf7a7fa>:0 
An error occurred when executing task 'Build'.
Error: XBuild: Process returned an error (exit code 1).
```

**Comment by conniey** [comment]
@aaubry I apologise, I misunderstood the failures as the errors you see on travis-ci as you made the updates.

I compiled the solution on Linux using Dustin's workaround but had to install mono msbuild (https://github.com/dotnet/sdk/issues/335#issuecomment-291487227):

```sh
# for Ubuntu 14.04 (trusty)
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install -y msbuild
sudo apt-get install -y dotnet-dev-1.0.3
```

Then to build:

```sh
dotnet restore YamlDotNet.sln
export DOTNETSDK=/usr/share/dotnet/sdk/1.0.3
export MSBuildExtensionsPath=$DOTNETSDK/
export CscToolExe=$DOTNETSDK/Roslyn/RunCsc.sh

msbuild /p:Configuration=Debug-AOT /t:Rebuild YamlDotNet.sln
```

**Comment by aaubry** [comment]
It's starting to look better. I installed msbuild, which was missing, and [updated the cake script](https://github.com/aaubry/YamlDotNet/compare/nbarbettini-netstandard...netstandard#diff-4d3634747586b964df9f7712bc3ec669R240) according to your comments.

Now I am able to successfully perform a debug build using:
```
> ./build.sh
```

But if I try to build all configurations, using:
```
> ./build.sh --target Build-Release-Configurations
```
then the build fails with this error:
```
CSC : error CS7027: Error signing output with public key from file '../YamlDotNet.snk' -- Assembly signing not supported. [/home/aaubry/Work/YamlDotNet/YamlDotNet/YamlDotNet.csproj]
```

I'll try to find a workaround.

**Comment by aaubry** [comment]
I noticed that my changes to the cake file did not fix the problem, I had left the environment variables set in my session. It also seems that the VS2017 image on AppVeyor does not have the required targets for the portable class library.

This looks like it will take a lot of work to fix all the issues, so first I would like you to explain me what we are trying to achieve. What problem are we trying to fix? As far as I can tell, everything is currently working correctly, and the library is already usable on .NET core. So what will be the benefit from changing the project to .NET core?

I am feeling that my time would be better spent on the other pending issues. Please convince me that I am wrong.

**Comment by nbarbettini** [comment]
> What problem are we trying to fix? As far as I can tell, everything is currently working correctly, and the library is already usable on .NET core. So what will be the benefit from changing the project to .NET core?

The library isn't completely usable on .NET Core. It's possible to use it by adding the [PackageTargetFallback](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj#imports) workaround, but it's awkward and (IIRC) that workaround is going to be deprecated eventually. The ideal going forward is for libraries to target some version of .NET Standard.

I'm not sure why AppVeyor is having so many problems, I haven't had a chance to circle back to this PR recently.

**Comment by conniey** [comment]
> It also seems that the VS2017 image on AppVeyor does not have the required targets for the portable class library.

I checked out the AppVeyor builds are failing because it is not actually using the Visual Studio 2017 image... It started working for me once I updated the appveyor.yml to include `image: Visual Studio 2017`.

> I noticed that my changes to the cake file did not fix the problem, I had left the environment variables set in my session. 

I was doing some research and it turns out that [Mono 5 Beta 2](http://www.mono-project.com/download/beta/) now supports .NET Core projects! (So no more of this environment variable hackery.) 

I've updated/created a PR against @nbarbettini 's branch where the builds should work in both CI builds and with Cake on Linux: https://github.com/nbarbettini/YamlDotNet/pull/1.  When he merges those changes in, you can use these steps to build YamlDotNet with build.cake:

```sh
# Install Mono 5.0 Beta 2 (5.0.0.94) (on Trusty) http://www.mono-project.com/download/beta/
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu beta-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-beta.list
sudo apt-get update
sudo apt-get update
sudo apt-get install mono-complete

# Install dotnet-dev 1.0.3
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install -y dotnet-dev-1.0.3

# Execute
./build.sh
```


> What problem are we trying to fix? As far as I can tell, everything is currently working correctly, and the library is already usable on .NET core. So what will be the benefit from changing the project to .NET core?
> The library isn't fully compatible with .NET Core. It's possible to use it by adding the PackageTargetFallback  workaround, but it's awkward and (IIRC) that workaround is going to be deprecated eventually. The ideal going forward is for libraries to target some version of .NET Standard.

In addition, to @nbarbettini's explanation, since this library is not fully compatible with .NET Standard and requires the use of PackageTargetFallback, it will not work with DotNetCliToolReferences (https://github.com/NuGet/Home/issues/3617).  I encountered this issue because I am trying to port GitVersionTask and GitVersion .NET Core CLI tool.

AFAIK, this is the most popular yaml parsing tool for .NET, so it would be nice if this were ported to .NET Core to make it easier for other 3rd party library developers who want to use this in their projects.

I understand the pains you are going through... I wish the mono/msbuild/.net core tooling experience on Linux was addressed earlier so these pains could be avoided.

**Comment by aaubry** [comment]
Ok, I am convinced :)

I am not comfortable in installing the beta version of mono on my system, because I use mono to run other apps, but thanks to your instructions, I managed to create a docker image that can run the build script without errors :+1:
That image might also be useful for the travis build, although you have already fixed it.
I still have a few minor issues, like the output path having an extra directory, e.g. `/bin/Release-Unsigned/net35`, which breaks the paths in the .nuspec files, but that should be easy to fix.

Tomorrow I will try to tie all loose ends and close this. Thanks to all for your patience and helpfulness!

**Comment by aaubry** [comment]
So, I made [more changes](https://github.com/aaubry/YamlDotNet/tree/netstandard) to the build script and to the nuspec files, mostly based on your branches.

I successfully ran a [build on AppVeyor](https://ci.appveyor.com/project/aaubry/yamldotnet/build/4.1.1-netstandard0378) that produced [this nuget package: YamlDotNet 4.1.1-netstandard0378](https://www.nuget.org/packages/YamlDotNet/4.1.1-netstandard0378). I successfully usied this package in a regular .NET application. I also tried using it in a .NET core application, but it did not work, but that may be due to my lack of knowledge.
What I did was:

```
> dotnet new console ConsoleApplication
> dotnet add package YamlDotNet --version [4.1.1-netstandard0378]
```

This second step failed with:
```
/usr/share/dotnet/sdk/1.0.3/NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 1.3.0)' for '.NETCoreApp,Version=v1.3'. [/home/aaubry/Work/YamlDotNet/samples/dotnetcore/ConsoleApplication.csproj]
```

If I change the `TargetFramework` from `netcoreapp1.3` to `netstandard1.3`, the `add package` command succeeds, but then I cannot run the application because the output is a .dll instead of an .exe.

Can someone help with this?

**Comment by Bond-009** [comment]
You can run it with `dotnet <dllfile>`

**Comment by stil** [comment]
@aaubry it's `netcoreapp1.1`, there is no such thing as `netcoreapp1.3` yet.

Check out this full list of netstandards:
https://docs.microsoft.com/en-us/nuget/schema/target-frameworks

Also:
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by aaubry** [comment]
Thanks, @stil , changing to `netcoreapp1.1` fixed the problem.
I think that the only issue that is left is to fix the Unity prequisites installation problem. I'll also need to merge the changes needed to build on Travis. Then I'll create a new PR with all the changes so that everybody interested can validate before I merge into master and publish a new release.

**Comment by nbarbettini** [comment]
I merged @conniey's PR into my fork, although I think @aaubry already grabbed the commits. 👍

**Comment by nbarbettini** [comment]
@aaubry I updated the Unity prerequisites install script to use 7zip, although it looks like you're changing the files so they aren't distributed via zip now. I missed that, so in case this is helpful: 😄 

```
$targets = @{
  'Unity Subset v3.5' = 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile'
  'UnityVS' = 'C:\Program Files (x86)\MSBuild\SyntaxTree'
}

$ExtractedPath = "$PSScriptRoot\extracted"
Write-Output "Extracting package.zip"
iex ".\7za.exe x package.zip -o$ExtractedPath"

$shell = new-object -com shell.application
$extracted = $shell.NameSpace("$ExtractedPath")

foreach($item in $extracted.items())
{
  $target = $targets[$item.Name]
  Write-Output "Copying $($item.Name) to $target"
  $d = mkdir $target -Force
  $shell.Namespace($target).copyhere($item)
}
```

**Comment by aaubry** [comment]
@nbarbettini I noticed that the Unity prerequisites are already installed on the VS2017 image, so that is no longer necessary, but thanks for the help.

**Comment by aaubry** [comment]
**All**, I have created [a new pull request](https://github.com/aaubry/YamlDotNet/pull/255) that contains most of the changes from this one, as well as all the changes that I needed to make to ensure that the builds [succeeded](https://ci.appveyor.com/project/aaubry/yamldotnet/build/4.1.1-netstandard0395) [everywhere](https://travis-ci.org/aaubry/YamlDotNet/builds/230141394), most of them taken directly from your comments.

Now I would like you to take a look at the PR, and also test the pre-release package [`4.1.1-netstandard0395`](https://www.nuget.org/packages/YamlDotNet/4.1.1-netstandard0395). Please be sure to install that specific version, because due to the sorting order of pre-release versions, an older package is seen as more recent.

Please let me know is you encounter any issue. If everything is good, I'll merge this into master and release a new version.

**Thanks to everyone who helped on this!**

**Comment by nbarbettini** [comment]
I'll take a look at the new PR and the prerelease package. Thanks for your work on this @aaubry!

**Comment by aaubry** [comment]
I am trying to convert the unit tests project so that the tests also run on the netstandard assembly, but it seems that FakeItEasy only supports netstandard1.6, while we are targeting netstandard1.3. Can we do anything about this?

**Comment by stil** [comment]
Can't we have unit tests targeting higher netstandard than library?

**Comment by aaubry** [comment]
We could probably, but I tried changing to netstandard1.6, but it seems that do not have the necessary requirements to compile for that target. I start getting errors like this:
```
error CS0518: Predefined type 'System.Object' is not defined or imported
```
I don't know how to fix that... :disappointed:

**Comment by Bond-009** [comment]
You need to dotnet restore

**Comment by conniey** [comment]
> We could probably, but I tried changing to netstandard1.6, but it seems that do not have the necessary requirements to compile for that target. I start getting errors like this:

Test projects should target netcoreapp1.0 or netcoreapp1.1 because they need to have a runtime.
http://xunit.github.io/docs/getting-started-dotnet-core

I have migrated the tests already. I am just trying to make them work on Linux and rebase them on your netstandard branch. https://github.com/conniey/YamlDotNet/tree/netstandard-tests

**Comment by aaubry** [comment]
I am closing this as the development of this was completed on another branch, which has been merged into master. I have released version [4.2.0](https://www.nuget.org/packages/YamlDotNet/4.2.0) which contains the new `netstandard1.3` assembly.
If you find anything that is not as it should, please open an issue.
**Thanks to all for your help!**

**Comment by MrM40** [comment]
Looking for .Net Core support this seems to do the job: https://github.com/xoofx/SharpYaml

**Comment by aaubry** [comment]
@MrM40, I don't know what you are trying to achieve with this comment. As indicated in the above comments, YamlDotNet has supposed netstandard for years now.

**Comment by aaubry** [comment]
In case it is not clear, support for netstandard also implies support for .NET Core.

**Comment by MrM40** [comment]
Really? I've looked every and you sure doesn't make it clear that it is the case. I was convinced you only supported .Net Framework and not Standard.

**Comment by conniey** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
.NET Core is a cross platform runtime that implements .NET Standard. .NET Core also includes runtime dependencies. If your library does not require runtime information, it would be best to target .NET Standard. 

You can imagine a new runtime, RuntimeX, that implements .NET Standard but has a different API surface area than .NET Core. If you targeted your library against netcoreapp, it wouldn't be able to run on RuntimeX. But one that compiled against .NET Standard could.

**Comment by aaubry** [comment]
@MrM40 You are correct, I shall add that information to the main readme. Currently it is hidden in the [CONTRIBUTING.md](https://github.com/aaubry/YamlDotNet/blob/master/CONTRIBUTING.md), which is not ideal.

For the record, the following platforms are supported by YamlDotNet:

   * .NET Framework 4.5
   * .NET Framework 3.5
   * .NET Framework 2.0
   * **.NET Standard 1.3**
  *  Unity Subset v3.5

Thanks for pointing this out.

**Comment by MrM40** [comment]
no no no....I'm fully aware about .Net Framework, .Net Standard and .Net Core.
To ask you to describe that here I would be a really big idiot!
What I mean is, it says nowhere that YamlDotNet support .Net Standard.
Take a look at the github [YamlDotNet ](https://github.com/aaubry/YamlDotNet )start page and the startpage of [SharpYaml](https://github.com/xoofx/SharpYaml).
See the different in the description of which .Net the library support?

**Comment by MrM40** [comment]
Then write it on the startpage. Should also be clear the NuGet page. 
And is it the same dll?

**Comment by aaubry** [comment]
I will do that. Regarding the dll, it is not the same. The NuGet package contains one dll for each platform, as normal.

**Comment by aaubry** [comment]
I have updated the readme to clarify the supported platforms. I still need to update the description on NuGet, as I realize that it is really outdated, but that will take a bit more time.

**Pull request closed without merging**
