### PR TITLE
Support struct aot

### PR DESCRIPTION
**Pull request by yhd4711499**

### CODE REVIEW

**Comment by yhd4711499** [comment]
Appveyor failed to build but no error message was shown. A rebuild should be triggered perhaps?

**Comment by EdwardCooke** [comment]
I think there’s a bug in the UI. At least on mobile. For the past few days I’ve had to download the log and view it from that. 

```
C:\projects\yamldotnet\YamlDotNet\Serialization\SerializerBuilder.cs(691,13): error IDE0074: Use compound assignment (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074) [C:\projects\yamldotnet\YamlDotNet\YamlDotNet.csproj::TargetFramework=net47]
[00:02:16] C:\projects\yamldotnet\YamlDotNet\Serialization\DeserializerBuilder.cs(488,13): error IDE0074: Use compound assignment (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074) [C:\projects\yamldotnet\YamlDotNet\YamlDotNet.csproj::TargetFramework=net47]
```

**Comment by yhd4711499** [comment]
Should I fix these "Use compound assignment" errors in current branch?

**Comment by EdwardCooke** [comment]
Yes please.

**Comment by yhd4711499** [comment]
I need some help in fixing formatting. I don't know what causes "error IDE0055: Fix formatting".

**Comment by yhd4711499** [comment]
All fixed.

**Pull request merged**
