### PR TITLE
Re-implementing Parser: Add support for multi-document tag directives

### PR DESCRIPTION
**Pull request by derFunk**
Especially to aid reading Unity scene files
Original PR https://github.com/aaubry/YamlDotNet/pull/102

### CODE REVIEW

**Comment by derFunk** [comment]
See also https://github.com/aaubry/YamlDotNet/issues/140

**Comment by aaubry** [comment]
This looks good, thanks! There was the question of the different behavior in YAML 1.2, but I think we can leave that for later.

There is just an issue with the formatting. This project uses tabs instead of spaces, and your changes are using spaces, which messes-up the alignment of blocks. Could you update the PR with tabs instead of spaces?

PS: I know that most people prefer to use spaces instead of tabs. I have opened a separate issue, #143 to discuss a possible move to that convention. Feel free to leave a comment there.

**Comment by aaubry** [comment]
I made the changes myself because I had to resolve a merge conflict.

**Comment by derFunk** [comment]
Ok, thanks a lot, I wasn't in reach of a PC this weekend :) :+1:

**Pull request merged**
