### PR TITLE
Throw an exception on duplicate keys

### LINKED ISSUE #536: Deserializing is not handling non-unique keys correctly
According to the YAML spec (and common sense) keys in YAML-mappings should be a set of unique values. I frequently encounter errors (originating from tiny typos of mine), where a document (or mapping within a document) like

```yml
fu: bar
fu: baz
```

is interpreted like 

```yml
fu: baz
```

and the duplicate key issue is silently ignored. 

Would it be possible to at least have an option to treat duplicate keys as deserialization errors?

### PR DESCRIPTION
**Pull request by nuttytree**
Deserializing YAML with non-unique keys throws a YamlException.  Resolves #536

### CODE REVIEW

**Comment by EdwardCooke** [comment]
I would prefer if this was done as an option and defaulted to the current behavior. In the deserializer builder, we would add another method, something like `ThrowExceptionOnDuplicateKeys`. That would set the feature flag to enable or disable this code.

**Comment by nuttytree** [comment]
I went without the option because duplicate keys are not valid YAML but I will update today to make it optional.

**Comment by EdwardCooke** [comment]
Changing the behavior of the library may cause unexpected issues for the consumers which is why I would like to see it as optional to opt in. Maybe in a future major version release we’ll make it the default.
________________________________

**Comment by nuttytree** [comment]
Sorry about the delay in getting this PR updated, been sucked into multiple things at work.  I have updated to make the duplicate key checking optional.  Let me know if you don't like the naming.

**Comment by EdwardCooke** [comment]
Merged! Yay.

**Comment by aaubry** [comment]
This feature has been released in [version 12.2.1](https://github.com/aaubry/YamlDotNet/releases/tag/v12.2.1).

**Pull request merged**
