### PR TITLE
Adds YamlPath Support

### LINKED ISSUE #333: Feature request: access YAML fields by string rather than full deserialization
Sometimes one just wants to ask questions about the YAML that's being processed rather than needing to deserialize it into an entire object graph. This is especially common when parts of the structure of the input are user-specified, as in the case of things like Kubernetes cluster definitions.

My ideal API would allow me to use `jq`-style lookups to enumerate over the YAML and retrieve the pieces of interest. For example, that might look like:

```
var reader = new FileReader("my-file.yaml");
var listOfAllPodNames = Yaml.Deserialize(reader)
                                  .Query(".pods[].name")
                                  .As(List<string>);
```

or

```
var mapOfPodAttributes = Yaml.Deserialize(reader)
                                  .Query(".pods[1].metadata")
                                  .As(Dictionary<string, string>);
```

or

```
Dictionary<string, string> mapOfPodAttributes = Yaml.Deserialize(reader)
                                  .Query(".pods[3].metadata")
                                  .As(Dictionary<string, string>[]);
```

Given the following YAML:

```
pods:
-
  name: alpha
  size: 1234
  metadata:
    label-one: four-five-six
-
  name: beta
  size: 3456
  metadata:
    label-two: three-seven-eight
    label-three: four-six-two
```

then we expect to see the following results:

```
// .pods[].name
string[]{"1234", "3456"}

// .pods[1].metadata
Dictionary<string, string> { {"label-one", "four-five-six"} }

// .pods[].metadata
Dictionary<string, string>[] {
  Dictionary<string, string>{ {"label-one", "four-five-six"} },
  Dictionary<string, string>{ {"label-two", "three-seven-eight"}, {"label-three", "four-six-two"} },
}
```

### PR DESCRIPTION
**Pull request by gfs**
Adds support for YamlPath queries as a `Query` extension method to `YamlNode`.

Basic Usage to search a whole document:

```csharp
using YamlDotNet.YamlPath;

YamlStream yaml = new YamlStream();
yaml.Load(new StringReader(targetYamlString));
YamlMappingNode mapping = (YamlMappingNode)yaml.Documents[0].RootNode;
IEnumerable<YamlNode> matching = mapping.Query(yourYamlPathQuery);
```

Fix #333

Implemented based on the YamlPath Spec located here: https://github.com/wwkimball/yamlpath/wiki/Segments-of-a-YAML-Path

Supported:
[Anchors](https://github.com/wwkimball/yamlpath/wiki/Segment:-Anchors)
[Array Elements](https://github.com/wwkimball/yamlpath/wiki/Segment:-Array-Elements)
[Array Element Searches](https://github.com/wwkimball/yamlpath/wiki/Segment:-Array-Element-Searches)
[Array Slices](https://github.com/wwkimball/yamlpath/wiki/Segment:-Array-Slices)
[Hash Attribute Searches](https://github.com/wwkimball/yamlpath/wiki/Segment:-Hash-Attribute-Searches)
[Hash Keys](https://github.com/wwkimball/yamlpath/wiki/Segment:-Hash-Keys)
[Hash Slices](https://github.com/wwkimball/yamlpath/wiki/Segment:-Hash-Slices)
[Pass-Through Selections for Arrays of Hashes](https://github.com/wwkimball/yamlpath/wiki/Segment:--Array-of-Hashes-Pass-Through-Selection)
[Search Keywords](https://github.com/wwkimball/yamlpath/wiki/Search-Keywords)
[Set Values](https://github.com/wwkimball/yamlpath/wiki/Segment:-Set-Values)
[Wildcard Segments](https://github.com/wwkimball/yamlpath/wiki/Wildcard-Segments)

Not supported:
[Collectors](https://github.com/wwkimball/yamlpath/wiki/Segment:-Collectors)

### CODE REVIEW

**Comment by EdwardCooke** [comment]
After leaving these comments and thinking about it, I'm wondering if this would be better suited to be in some kind of extension package and not necessarily brought in to the main YamlDotNet package. I didn't notice anything in there that would require access to any of the internals of YamlDotNet. Not sure when we would get time to do that though. Thoughts?

**Comment by gfs** [comment]
@EdwardCooke I don't see any other comments but I'm happy to address any feedback or concerns.

It makes sense to me as a separate extensions package.  I'm happy to refactor the PR to be its own extensions csproj if that would help.

**Comment by gfs** [comment]
@EdwardCooke I refactored the YamlPath implementation into its own csproj.  I based the csproj heavily on the csproj for the main project - however, I was receiving a build error about the visibility of the AssemblyInformation attribute when including net4.0, so I have excluded it for now. I don't normally target so many net versions so I'm not sure how to resolve the net4.0 issue.

**Comment by gsw945** [comment]
**YamlPath**  feature is what i needed 👍

**Comment by gfs** [comment]
@gsw945 

I have forked this into its own repository and am publishing a Nuget you can consume.

Repo: https://github.com/gfs/YamlPathForYamlDotNet
Nuget: https://www.nuget.org/packages/gstocco.YamlDotNet.YamlPath

**Pull request closed without merging**
