### PR TITLE
add struct support for AOT

### PR DESCRIPTION
**Pull request by yhd4711499**

### CODE REVIEW

**Comment by EdwardCooke** [comment]
You’ll need to reopen this or from a branch not named master. Also, can you please add a test for this?

**Comment by yhd4711499** [comment]
sure thing

**Comment by yhd4711499** [comment]
sorry I dont know how to reopen this pull request. I've created a new one.

**Comment by EdwardCooke** [comment]
That’s what I was meaning. Sorry I wasn’t more clear.

**Pull request closed without merging**
