### PR TITLE
Add support for supplying custom IObjectGraphTraversalStrategy implementations  

### PR DESCRIPTION
**Pull request by psaxton**
Allows for custom object graph traversal strategies to be implemented and used by the Serializer.

### CODE REVIEW

**Comment by psaxton** [comment]
Check failure is `Cake.exe : An error occurred when executing task 'Set-Build-Version'.`. This appears to be a problem with the build pipeline rather than my changes.

**Comment by psaxton** [comment]
I fixed the build errors in a seperate PR #363 and merged those changes to this PR so it should be actionable. Please advise.

**Comment by aaubry** [comment]
Thanks, I've merged your changes and a new release is currently building.

**Comment by psaxton** [comment]
Thanks!

**Pull request merged**
