### PR TITLE
Fix block entry indicator check

### LINKED ISSUE #709: Invalid key indicator format after upgrade to 12.0.0
**Describe the bug**

Following YAML  checks out as valid in online parsers:

```yaml
es5id: 11.4.7-4-1
description: -"" should be zero
```

but after upgrade from 11.2.1 to 12.0.0 it started to fail with message:

```
YamlDotNet.Core.SemanticErrorException
Invalid key indicator format.
   at YamlDotNet.Core.Parser.ParseNode(Boolean isBlock, Boolean isIndentlessSequence) in C:\Work\YamlDotNet\YamlDotNet\Core\Parser.cs:line 462
   at YamlDotNet.Core.Parser.ParseBlockMappingValue() in C:\Work\YamlDotNet\YamlDotNet\Core\Parser.cs:line 833
   at YamlDotNet.Core.Parser.StateMachine() in C:\Work\YamlDotNet\YamlDotNet\Core\Parser.cs:line 158
   at YamlDotNet.Core.Parser.MoveNext() in C:\Work\YamlDotNet\YamlDotNet\Core\Parser.cs:line 107
   at YamlDotNet.Core.ParserExtensions.Consume[T](IParser parser) in C:\Work\YamlDotNet\YamlDotNet\Core\ParserExtensions.cs:line 43
```

**To Reproduce**

```csharp
[Fact]
public void InvalidKeyIndicatorFormat()
{
    var yamlStream = new YamlStream();
    yamlStream.Load(new StringReader("description: -\"\" should be zero"));
}
```

**Possible fix**

Removing `\"` from below check seems to fix the issue, but not sure something else will be broken...

https://github.com/aaubry/YamlDotNet/blob/fd6731d4ab6bb4f3bec79a47b9ecb60f0d8e415f/YamlDotNet/Core/Scanner.cs#L401-L404

### LINKED ISSUE #719: Special string triggers SemanticErrorException: Invalid key indicator format
**Describe the bug**
Round trip of certain plain strings is handled incorrectly.
May be similar to #709.
Version: 12.0.0

**To Reproduce**
```
  var serializer = new YamlDotNet.Serialization.SerializerBuilder().Build();
  string yaml = serializer.Serialize(new System.Collections.Generic.Dictionary<string, string>() {
      { "symbol_1", "-@" },
      { "symbol_2", "-&" }
  });
  var deserializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
  var dict = deserializer.Deserialize<System.Collections.Generic.Dictionary<string, string>>(yaml);
```
```
YamlDotNet.Core.SemanticErrorException
  HResult=0x80131500
  Message=Invalid key indicator format.
  Source=YamlDotNet
  StackTrace:
   at YamlDotNet.Core.Parser.ParseNode(Boolean isBlock, Boolean isIndentlessSequence)
   at YamlDotNet.Core.Parser.ParseBlockMappingValue()
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
```

### PR DESCRIPTION
**Pull request by lahma**
fixes #709
fixes #719

### CODE REVIEW

**Comment by EdwardCooke** [comment]
I’ll look this over later today. I want to double check the yaml spec first.

**Comment by EdwardCooke** [comment]
I appologize for the really long delay, had some family stuff to deal with. Anyways, the check should only be for the following characters `,[]{}`. If you update your PR with that then I'll merge it in.

**Comment by lahma** [comment]
@EdwardCooke I've force-pushed an updated version based on the spec you gave, sorry for the delay!

**Comment by EdwardCooke** [comment]
Great. I’ll try and get this out today or tomorrow.

**Comment by aaubry** [comment]
This feature has been released in [version 12.0.1](https://github.com/aaubry/YamlDotNet/releases/tag/v12.0.1).

**Pull request merged**
