### PR TITLE
Issue#601 Support for deserialization of interface types

### PR DESCRIPTION
**Pull request by dotlegacy**
…ir concrete types using the builder.AddTypeMapping<TInterface, TConcrete>() api.

## Welcome!

Thanks for your interest in contributing to this project. Any contribution will
be gladly accepted, provided that they are generally useful and follow the
conventions of the project.

1. Please create **one pull request for each feature**. This results in smaller pull requests that are easier to review and validate.

1. **Avoid reformatting existing code** unless you are making other changes to it.  
   - Cleaning-up of `using`s is acceptable, if you made other changes to that file.
   - If you believe that some code is badly formatted and needs fixing, isolate that change in a separate pull request.

1. Always add one or more **unit tests** that prove that the feature / fix you are submitting is working correctly.

1. Please **describe the motivation** behind the pull request. Explain what was the problem / requirement. Unless the implementation is self-explanatory, also describe the solution.
   * Of course, there's no need to be too verbose. Usually one or two lines will be enough.

1. Follow the project's [coding conventions](CONTRIBUTING.md#coding-style)

### CODE REVIEW

**Comment by dotlegacy** [comment]
This is related to issue #604

**Comment by aaubry** [comment]
This looks really good. Thanks!

**Comment by aaubry** [comment]
This heature has been released in [version 11.1.0](https://github.com/aaubry/YamlDotNet/releases/tag/v11.1.0).

**Comment by dotlegacy** [comment]
> This looks really good. Thanks!

Thank you for the starting this project!  I also noticed that your code coverage configuration needs to be updated so that it shouldn't count any other code than the main project.  I will push another PR to address that unless you disagree.

**Comment by aaubry** [comment]
Sure. I wasn't aware that code coverage was even being measured, but of course it's better to make it accurate.

8 Apr 2021 17:54:49 dotlegacy ***@***.***>:

**Pull request merged**
