### PR TITLE
VS 2022, Unit Tests and fixes

### PR DESCRIPTION
**Pull request by EdwardCooke**
* Added support for working in VS 2022
  * Required removing .net 2.0 from the targets
* Updated unit tests to latest supplied from yaml
* Fixed the bugs found by the new unit tests
* Added netstandard 2.0 to the target frameworks

#672 #650

### CODE REVIEW

**Comment by EdwardCooke** [comment]
@JuergenGutsch here's a PR to get this project ready to get some more bug fixes done. Let me know what you think and I'll resolve whatever concerns or start getting to work on the other issues people are having.

**Review by JuergenGutsch — APPROVED** [review]
looks good to me

**Comment by JuergenGutsch** [comment]
@aaubry The updated Readme is already in the PR

**Comment by lahma** [comment]
Sorry to comment on closed PR, just a note and whether makes sense for further actions. For new releases, does it makes sense to support targets that have hit end of life? I'm not a Unity developer (hopefully there's someone in this community to verify my claims), but with [Jint](https://github.com/sebastienros/jint) we've just dropped anything below net462 and netstandard2.0.

This makes contributing easier as you don't need to install special workloads to support legacy targets and I believe Unit now has netstandard2.0 support. So might make it easier to drop legacy support especially if the project is going to have a "clean slate/reboot".

**Comment by aaubry** [comment]
This feature has been released in [version 12.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v12.0.0).

**Pull request merged**
